"""
tests/test_pipeline.py

Regression tests using synthetic fixtures (no customer artwork).
Fixtures are generated by tests/make_fixtures.py and committed.
"""

from __future__ import annotations
import os
import sys
import tempfile
import pytest
import pikepdf

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.pdf.parser import extract_cutcontour_paths, ParseError
from app.pdf.writer import append_perfcut_contour
from app.pdf.verify import verify_output, collect_page_boxes, VerifyError
from app.geometry.offset import offset_polygons
from app.core import process_pdf

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")
INPUT_PDF = os.path.join(FIXTURES, "input_cutcontour.pdf")
NO_CC_PDF = os.path.join(FIXTURES, "no_cutcontour.pdf")

PT_TO_MM = 25.4 / 72.0
OFFSET_MM = 2.5


# ---------------------------------------------------------------------------
# Shared fixture: run the full pipeline once per test session
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def processed_pdf_path():
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        tmp_path = f.name
    try:
        process_pdf(INPUT_PDF, tmp_path)
        yield tmp_path
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _spot_names(page: pikepdf.Page) -> set[str]:
    res = page.obj.get("/Resources") or {}
    cs = res.get("/ColorSpace") if res else None
    if not cs:
        return set()
    names = set()
    for k in cs.keys():
        e = cs[k]
        if isinstance(e, pikepdf.Array) and len(e) >= 2 and str(e[0]) == "/Separation":
            names.add(str(e[1]).lstrip("/"))
    return names


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_input_has_cutcontour():
    pdf = pikepdf.open(INPUT_PDF)
    names = _spot_names(pdf.pages[0])
    pdf.close()
    assert "CutContour" in names


def test_extract_returns_polygons():
    pdf = pikepdf.open(INPUT_PDF)
    polys = extract_cutcontour_paths(pdf.pages[0])
    pdf.close()
    assert len(polys) >= 1
    assert all(len(p) >= 3 for p in polys)


def test_cutcontour_bbox_matches_expected():
    """Synthetic CutContour must be exactly 48×50 mm."""
    pdf = pikepdf.open(INPUT_PDF)
    polys = extract_cutcontour_paths(pdf.pages[0])
    pdf.close()
    xs = [p[0] for poly in polys for p in poly]
    ys = [p[1] for poly in polys for p in poly]
    w_mm = (max(xs) - min(xs)) * PT_TO_MM
    h_mm = (max(ys) - min(ys)) * PT_TO_MM
    assert abs(w_mm - 48.0) < 0.1, f"Width should be 48 mm, got {w_mm:.3f}"
    assert abs(h_mm - 50.0) < 0.1, f"Height should be 50 mm, got {h_mm:.3f}"


def test_offset_distance_is_2_5mm():
    pdf = pikepdf.open(INPUT_PDF)
    polys = extract_cutcontour_paths(pdf.pages[0])
    pdf.close()
    offset_polys = offset_polygons(polys, OFFSET_MM)

    xs_in  = [p[0] for poly in polys for p in poly]
    ys_in  = [p[1] for poly in polys for p in poly]
    xs_out = [p[0] for poly in offset_polys for p in poly]
    ys_out = [p[1] for poly in offset_polys for p in poly]

    tol = 0.05  # mm
    for label, val in [
        ("left",  (min(xs_in) - min(xs_out)) * PT_TO_MM),
        ("right", (max(xs_out) - max(xs_in)) * PT_TO_MM),
        ("down",  (min(ys_in) - min(ys_out)) * PT_TO_MM),
        ("up",    (max(ys_out) - max(ys_in)) * PT_TO_MM),
    ]:
        assert abs(val - OFFSET_MM) < tol, f"Offset {label}: expected {OFFSET_MM} mm, got {val:.4f} mm"


def test_output_has_both_spot_colors(processed_pdf_path):
    pdf = pikepdf.open(processed_pdf_path)
    names = _spot_names(pdf.pages[0])
    pdf.close()
    assert "CutContour" in names, "CutContour must remain in output"
    assert "PerfCutContour" in names, "PerfCutContour must be added"


def test_perfcutcontour_is_separation(processed_pdf_path):
    pdf = pikepdf.open(processed_pdf_path)
    page = pdf.pages[0]
    cs_dict = page.obj["/Resources"]["/ColorSpace"]
    found = False
    for k in cs_dict.keys():
        e = cs_dict[k]
        if isinstance(e, pikepdf.Array) and len(e) >= 2:
            if str(e[0]) == "/Separation" and str(e[1]) == "/PerfCutContour":
                found = True
                assert str(e[2]) == "/DeviceCMYK"
                c1 = e[3]["/C1"]
                assert abs(float(str(c1[0])) - 1.0) < 0.01, "C should be 1.0"
                assert abs(float(str(c1[1])) - 0.0) < 0.01, "M should be 0.0"
                assert abs(float(str(c1[2])) - 1.0) < 0.01, "Y should be 1.0"
                assert abs(float(str(c1[3])) - 0.0) < 0.01, "K should be 0.0"
    pdf.close()
    assert found, "PerfCutContour Separation not found"


def test_perfcutcontour_has_stroke_overprint(processed_pdf_path):
    """PerfCutContour must be stroked with /OP true ExtGState."""
    pdf = pikepdf.open(processed_pdf_path)
    page = pdf.pages[0]
    res = page.obj["/Resources"]

    # Find PerfCutContour CS key
    cs_dict = res["/ColorSpace"]
    pcc_cs_key = None
    for k in cs_dict.keys():
        e = cs_dict[k]
        if isinstance(e, pikepdf.Array) and len(e) >= 2:
            if str(e[0]) == "/Separation" and str(e[1]) == "/PerfCutContour":
                pcc_cs_key = str(k)
                break
    assert pcc_cs_key is not None

    # Find ExtGState with /OP true
    egs_dict = res.get("/ExtGState")
    assert egs_dict is not None, "No ExtGState in resources"
    op_gs_key = None
    for k in egs_dict.keys():
        if egs_dict[k].get("/OP") == True:  # noqa: E712
            op_gs_key = str(k)
            break
    assert op_gs_key is not None, "No ExtGState with /OP true"

    # Verify content stream applies gs before stroking PerfCutContour
    ops = list(pikepdf.parse_content_stream(page))
    current_cs = None
    gs_applied = False
    gs_before_stroke = False
    for operands, op in ops:
        name = str(op)
        if name == "gs" and str(operands[0]) == op_gs_key:
            gs_applied = True
        elif name == "CS":
            current_cs = str(operands[0])
            if current_cs != pcc_cs_key:
                gs_applied = False
        elif name in ("S", "s", "B", "b") and current_cs == pcc_cs_key and gs_applied:
            gs_before_stroke = True
        elif name == "Q":
            gs_applied = False
            current_cs = None
    pdf.close()
    assert gs_before_stroke, "PerfCutContour stroke not preceded by overprint ExtGState"


def test_page_boxes_unchanged(processed_pdf_path):
    pdf_in = pikepdf.open(INPUT_PDF)
    orig = collect_page_boxes(pdf_in.pages[0])
    pdf_in.close()

    pdf_out = pikepdf.open(processed_pdf_path)
    out = collect_page_boxes(pdf_out.pages[0])
    pdf_out.close()

    for name in ("MediaBox", "TrimBox", "BleedBox"):
        if orig.get(name) is not None:
            assert str(orig[name]) == str(out[name]), f"{name} changed"


def test_output_can_be_reopened(processed_pdf_path):
    pdf = pikepdf.open(processed_pdf_path)
    assert len(pdf.pages) == 1
    pdf.close()


def test_verify_passes(processed_pdf_path):
    verify_output(processed_pdf_path)


def test_verify_fails_on_missing_perfcut():
    with pytest.raises(VerifyError, match="PerfCutContour"):
        verify_output(INPUT_PDF)


def test_no_cutcontour_raises_parseerror():
    pdf = pikepdf.open(NO_CC_PDF)
    with pytest.raises(ParseError, match="CutContour"):
        extract_cutcontour_paths(pdf.pages[0])
    pdf.close()


def test_process_pdf_function():
    """process_pdf() callable independently of HTTP (for future Drive worker)."""
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        out = f.name
    try:
        process_pdf(INPUT_PDF, out)
        pdf = pikepdf.open(out)
        names = _spot_names(pdf.pages[0])
        pdf.close()
        assert "PerfCutContour" in names
    finally:
        os.unlink(out)
